In [1]:
import cv2
import numpy as np

ann = cv2.ml.ANN_MLP_create()
ann.setLayerSizes(np.array([2, 3, 2], dtype=np.uint8))
#ann.setActivationFunction(cv2.ml.ANN_MLP_SIGMOID_SYM,1,1)
ann.setActivationFunction(cv2.ml.ANN_MLP_GAUSSIAN,1,1)
ann.setTrainMethod(cv2.ml.ANN_MLP_BACKPROP)
#ann.setTrainMethod(cv2.ml.ANN_MLP_RPROP)


A = np.array([[18,18],[20,18],[13,5],[1,25],[49,30],
             [60,88],[70,52],[80,64],[92,55],[75,66]])

B = np.array([[23,60],[20,80],[40,56],[15,95],[2,91],
             [55,11],[92,12],[52,8],[62,33],[88,45]])

trainData = np.concatenate((A,B),axis=0)
trainData = np.array(trainData, dtype=np.float32)
classData = np.array([[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],[1, 0],
                      [0, 1],[0, 1],[0, 1],[0, 1],[0, 1],[0, 1],[0, 1],[0, 1],[0, 1],[0, 1]])
classData = np.array(classData, dtype=np.float32)
print(trainData)
print(classData)

ann.train(np.array(trainData, dtype=np.float32), cv2.ml.ROW_SAMPLE, classData)

X = np.random.random_integers(100, size=(1000,2))
X = np.array(X, dtype=np.float32)

resultados = ann.predict(X)

print(resultados[1])

plt.figure(0)
plt.plot(A[:,0],A[:,1],'ro')
plt.plot(B[:,0],B[:,1],'go')

for i in range(len(X)):
    if(resultados[1][i,0]>resultados[1][i,1]):
        plt.plot(X[i,0],X[i,1],'bo')
    else:
        plt.plot(X[i,0],X[i,1],'yo')

plt.xlim([0,100])
plt.ylim([0,100])
plt.show()


[[18. 18.]
 [20. 18.]
 [13.  5.]
 [ 1. 25.]
 [49. 30.]
 [60. 88.]
 [70. 52.]
 [80. 64.]
 [92. 55.]
 [75. 66.]
 [23. 60.]
 [20. 80.]
 [40. 56.]
 [15. 95.]
 [ 2. 91.]
 [55. 11.]
 [92. 12.]
 [52.  8.]
 [62. 33.]
 [88. 45.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[0.9831249  0.12684856]
 [0.38802713 0.902294  ]
 [0.46537632 0.7607494 ]
 ...
 [0.09793399 0.6860901 ]
 [0.9594402  0.22417131]
 [0.21214609 0.39944613]]


C:\Users\hp\Anaconda2\lib\site-packages\ipykernel_launcher.py:28: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead


NameError: name 'plt' is not defined